### ISSUE TITLE
Broken build?

### ISSUE THREAD

**Issue by amites** [SlicingDice/slicingdice-javascript#27]
Come on @joaosimbiose, how did you push out a release when CI is broken?

https://circleci.com/gh/SlicingDice/slicingdice-javascript/177

I'll likely submit a PR next week if still broken, but for real -- SlicingDice is not cheap software -- leaving a core library broken for weeks on end is just sloppy and reflects very poorly on the company that I'm preparing to have host significant amounts of my customer data

**Comment by joaosimbiose** [comment]
Hi @amites,

Sorry for the late response, the build is just broken because the configuration of CircleCI has some bugs. The client itself doesn't have any bug, we did all the tests on some internal machines and everything works. 

We will never add code to the master branch without validating before, it's just the way that we make the tests on the CircleCI that is making the build to fail.

We're just validating the migration to a new CI tool to correct these errors. Sorry about that.

If you have any other question just let me know.

Thanks,
João.

**Comment by amites** [comment]
Cool -- perhaps next time add a note to the PR :+1:
